unstable_features = true
blank_lines_upper_bound = 2
where_single_line = true

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
trailing_comma = "Always"


wrap_comments = true
comment_width = 100
